language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "pypy"
matrix:
  allow_failures:
    - python: "3.7"
    - python: "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov pytest-xdist coveralls coverage

# command to run tests
script: py.test -v --cov edx_dl --cov-report html

after_success:
  coveralls

notifications:
  email:
    - csyzheng@gmail.com
